# server port ?? ??
server:
  port: 8082

# data base ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_springboot1
    password: 1234

  # thymeleaf ?? ??
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      # spring.jpa.hibernate.ddl-auto=create
      ddl-auto: update

# db query log ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace